export const GET_PLACES_LIST = 'GET_PLACES_LIST';
export const GET_PLACES_LIST_COMPLETE = 'GET_PLACES_LIST_COMPLETE';
export const GET_PLACE_DETAILS_COMPLETE = 'GET_PLACE_DETAILS_COMPLETE';
export const GET_PAYMENT_TYPES_COMPLETE = 'GET_PAYMENT_TYPES_COMPLETE';
